dataset:
  mode: clean #clean | emi+clean | emi
  root: "SavedDataSets"
  num_iq_samples_dataset: 32768
  fft_size: 512
  sample_rate: 200000
  seed: 123456789
  signal_center_freq_min: -0.3
  signal_center_freq_max: 0.3
  signal_duration_in_samples_min: 12288 #Min range is great for spectrum analysis + EMI research
  signal_duration_in_samples_max: 16384 #Max range is great for spectrum analysis + EMI research
  signal_bandwidth_freq_min: -0.4
  signal_bandwidth_freq_max: 0.4
  signal_bandwidth_min: 20000
  signal_bandwidth_max: 60000

class_list:
  clean:
    - bpsk
    - qpsk
  emi+clean:
    clean:
      - bpsk
      - qpsk
    emi:
      - tone

num_signals:
  clean:
    num_signals_min: 1
    num_signals_max: 3
  emi+clean:
    num_signals_min: 1
    num_signals_max: 3
  emi:
    num_signals_min: 0
    num_signals_max: 1

snr_db:
  clean:
    snr_db_min: 10
    snr_db_max: 20

  emi:
    snr_db_min: 1
    snr_db_max: 20

  emi+clean:
      snr_db_min: 10
      snr_db_max: 20


noise_power: -30
dataset_length: 10000


training:
 batch_size: 8
 epochs: 20
 seed: 42

validation:
  batch_size: 8
  seed: 43
test:
  batch_size: 10
  seed: 44








